<a id="inicio"></a>

# Movie Database ETL Pipeline

## Objective

Build an end-to-end data engineering pipeline that acquires movie metadata from multiple heterogeneous sources, stages it in a document store, then consolidates it into a normalized relational database for analytical querying.

## Methodology

- **Source 1 — IMDb bulk TSVs**: Load `title.basics.tsv.gz` and `title.ratings.tsv.gz`, select movies with 50k+ votes
- **Source 2 — TMDb REST API**: Enrich each selected movie with plot, budget, revenue, cast and crew
- **Staging — MongoDB Atlas**: Land raw JSON responses into a NoSQL document store (`dbmovies` database)
- **Transform — pandas**: Explode nested cast/crew arrays, normalize to long-form `df_movies`, `df_people`, `df_credits`
- **Load — SQLite**: Define a relational schema with foreign keys across `MOVIES`, `PEOPLE`, `CREDITS`, bulk-load from pandas
- **Query — SQL**: Demonstrate analytical queries against the resulting relational database

## Setup

This notebook requires credentials and external services:

```python
# Environment variables expected (set before running)
# TMDB_TOKEN        - TMDb API v3 read token
# MONGODB_URI       - MongoDB Atlas connection string
# CIDAEN_API_KEY    - API key for the internal people/keywords collection
```

Input files (place in `data/`): `title.basics.tsv.gz`, `title.ratings.tsv.gz` (distributed via [IMDb Datasets](https://datasets.imdbws.com)).

---

<div class="alert alert-block alert-info">

### ℹ️ Note on cell outputs

The cell outputs visible in this notebook were captured during the **original run** and are shown here as a visual reference for portfolio review. Some artifacts may still appear in Spanish — DataFrame column headers, axis labels on plots, printed messages — because the outputs predate the English code translation. Re-executing the notebook top-to-bottom will regenerate every output in English (where applicable).

**To re-run locally:**

1. Clone the repo and create a Python 3.9+ virtual environment:
   `python -m venv .venv && source .venv/bin/activate`
2. Install dependencies:
   `pip install -r requirements.txt`
3. Place the required input files under `data/` (see repo README or this notebook's setup cells for the exact list).
4. Provide the required credentials as environment variables before launching Jupyter:
   - `TMDB_TOKEN` — TMDb v4 API Read Token ([request here](https://www.themoviedb.org/settings/api))
   - `MONGODB_URI` — your own MongoDB Atlas connection string (the notebook uses a `dbmovies` database with `movies`, `credits`, and `people` collections)
   - `CIDAEN_API_KEY` — only needed for the optional people-enrichment section in 2.4; without it, skip cells in that section

   Then update cells 28 and 56 to read from the env vars (e.g. `token = os.environ["TMDB_TOKEN"]`) and wire up the MongoDB URI to `os.environ["MONGODB_URI"]`.

5. Launch Jupyter:
   `jupyter lab` (or `jupyter notebook`), open this file, select the venv kernel, and run every cell top-to-bottom.

</div>

---

---

This project covers the first stage of the data lifecycle — acquisition, storage, and preparation. Data is pulled from sources of different natures (bulk TSVs, REST APIs, an internal Mongo-backed HTTP endpoint) and staged in semi-structured form before being processed and loaded into a relational database that supports analytical queries. The workflow mirrors a small-scale data engineering pipeline: raw data lands in an unstructured store, then is extracted, prepared, and organized according to its eventual use.

<div class="alert alert-block alert-warning">
<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
Given the notebook's size and internal link structure, it's recommended to open it with `jupyter nbclassic`.
</div>

---

<a id="indice"></a>
## Contents

* [1. Download and Selection of IMDb Data](#section1)
   * [1.1 Reading IMDb Data](#section11)
   * [1.2 Title Selection](#section12)

* [2. Acquiring Data from TMDb](#section2)
   * [2.1 Fetching Movie Information](#section21)
   * [2.2 MongoDB Storage](#section22)
   * [2.3 Downloading Credits](#section23)
   * [2.4 People Data](#section24)

* [3. Building a Structured Dataset](#section3)
   * [3.1 DataFrame Construction](#section31)
   * [3.2 Relational Database Schema and Load](#section32)

* [4. Example Queries](#section4)
* [5. Conclusions](#section5)

* [A. Optional Extensions](#sectionA)
    * [A.1 Keywords](#sectionA1)
    * [A.2 TV Series and Episodes](#sectionA2)

---

In [1]:
# Display options
from IPython.display import display, HTML, Image

display(HTML("<style>.container{ width:95%}</style>"))
%matplotlib inline
%config InlineBackend.figure_format = 'retina'


# Work around occasional TLS issues with API calls
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

---

<a id="section1"></a>
## 1. Download and Selection of IMDb Data

*Internet Movie Database ([IMDb](http://www.imdb.com))* is one of the canonical online catalogs for films and TV series. IMDb explicitly prohibits scraping but publishes a subset of its catalog as downloadable CSV/TSV files ([datasets](https://datasets.imdbws.com)). The schemas are limited, but they are a solid starting point for building a richer dataset from additional sources.

This project uses two files (as of December 2023):

* `data/title.basics.tsv.gz` — basic title metadata (movies, series, episodes, etc.)
* `data/title.ratings.tsv.gz` — ratings and vote counts per title

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

<a id="section11"></a>
### 1.1 Reading IMDb Data

Load both files into `df_titles` and `df_ratings`, using the first column as the index in each. Columns are tab-separated; missing values are encoded as `\N`. The `.tsv.gz` files can be read directly by `pd.read_csv()` using `compression='gzip'`; reading takes a few seconds because `title.basics` decompresses to just under 1 GB.

A quick look at `title.basics.tsv.gz` shows four columns that should be nullable integers. We declare `isAdult`, `startYear`, and `endYear` as `Int32` up front via the `dtype` argument.

In [ ]:
# Display full DataFrames with row counts visible
import pandas as pd
pd.options.display.max_rows = 6
pd.options.mode.copy_on_write = True

num_types ={
    'titleType':'string',
    'primariTitle':'string',
    'originalTitle':'string',
    'genres':'string',
    'isAdult':'Int32',
    'startYear':'Int32',
    'endYear':'Int32',
}


df_titles = pd.read_csv('data/title.basics.tsv.gz',sep='\t',na_values='\\N',compression='gzip',dtype=num_types)
df_titles.head()

:

`runtimeMinutes` cannot be cast at read time — a handful of rows contain string values that confuse the type coercion. We handle it in two steps: `pd.to_numeric(..., errors='coerce')` turns non-numeric values into NaN, then `Series.astype('Int32')` gives us the nullable integer dtype we want.

In [4]:
df_titles['runtimeMinutes'] = pd.to_numeric(df_titles['runtimeMinutes'], errors='coerce').astype('Int32')
df_titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11217433 entries, 0 to 11217432
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          object
 1   titleType       string
 2   primaryTitle    object
 3   originalTitle   string
 4   isAdult         Int32
 5   startYear       Int32
 6   endYear         Int32
 7   runtimeMinutes  Int32
 8   genres          string
dtypes: Int32(4), object(2), string(3)
memory usage: 641.9+ MB

In [5]:
df_titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11217433 entries, 0 to 11217432
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          object
 1   titleType       string
 2   primaryTitle    object
 3   originalTitle   string
 4   isAdult         Int32
 5   startYear       Int32
 6   endYear         Int32
 7   runtimeMinutes  Int32
 8   genres          string
dtypes: Int32(4), object(2), string(3)
memory usage: 641.9+ MB

Load `data/title.ratings.tsv.gz` into `df_ratings` with the same conventions.

In [6]:
df_ratings = pd.read_csv('data/title.ratings.tsv.gz',sep='\t',na_values='\\N',compression='gzip')
df_ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1495761 entries, 0 to 1495760
Data columns (total 3 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   tconst         1495761 non-null  object
 1   averageRating  1495761 non-null  float64
 2   numVotes       1495761 non-null  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 34.2+ MB

All three DataFrames are now loaded and indexed by `tconst`, the unique identifier for each IMDb title.

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

<a id="section12"></a>
### 1.2 Title Selection

The raw files contain millions of rows, and many ratings are backed by a handful of votes. Here we filter down to the subset of titles that matter for the rest of the project.

The next cell previews the `titleType` values in `df_titles`.

In [7]:
df_titles['titleType'].unique()

<StringArray>
[       'short',        'movie',      'tvShort',      'tvMovie',
    'tvEpisode',     'tvSeries', 'tvMiniSeries',    'tvSpecial',
        'video',    'videoGame',      'tvPilot']
Length: 11, dtype: string

#### Movie selection

Build a `df_movies` DataFrame containing only `titleType == 'movie'` rows from `df_titles`, joined with their rating and vote count. Keep only titles with strictly more than 50,000 votes. This filter produces ~4,073 movies.

In [8]:
df_titles.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,<NA>,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,<NA>,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,<NA>,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,<NA>,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,<NA>,1,"Comedy,Short"

In [9]:
df_ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2096
1  tt0000002            5.6       282
2  tt0000003            6.5      2115
3  tt0000004            5.4       182
4  tt0000005            6.2      2845

In [10]:
df_movies = (
    pd.merge(
        df_titles,
        df_ratings[df_ratings['numVotes']>50000],
        on = 'tconst',
        how='inner'
    )
)

In [27]:
df_movies.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
0,tt0000417,short,A Trip to the Moon,Le voyage dans la lune,0,1902,<NA>,13,"Action,Adventure,Comedy",8.1,57200
1,tt0010323,movie,The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,0,1920,<NA>,67,"Horror,Mystery,Thriller",8.0,71863
2,tt0012349,movie,The Kid,The Kid,0,1921,<NA>,68,"Comedy,Drama,Family",8.2,137619
3,tt0013442,movie,Nosferatu: A Symphony of Horror,"Nosferatu, eine Symphonie des Grauens",0,1922,<NA>,94,"Fantasy,Horror",7.8,108889
4,tt0015324,movie,Sherlock Jr.,Sherlock Jr.,0,1924,<NA>,45,"Action,Comedy,Romance",8.2,58967

#### Memory reclaim

With `df_movies` assembled, `df_titles` and `df_ratings` can be released from memory — they are large and no longer needed.

In [11]:
df_titles.memory_usage(deep=True)

Index                   132
tconst            745934134
titleType         731840696
                    ...
endYear            56087165
runtimeMinutes     56087165
genres            764405392
Length: 10, dtype: int64

In [12]:
import gc

del df_titles
del df_ratings

gc.collect();

In [13]:
df_movies.to_feather("df_movies.feather")  #storing merged df for future loads

In [2]:
import pandas as pd
df_movies = pd.read_feather("df_movies.feather")

In [3]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4976 entries, 0 to 4975
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tconst          4976 non-null   object
 1   titleType       4976 non-null   string
 2   primaryTitle    4976 non-null   object
 3   originalTitle   4976 non-null   string
 4   isAdult         4976 non-null   Int32
 5   startYear       4976 non-null   Int32
 6   endYear         492 non-null    Int32
 7   runtimeMinutes  4955 non-null   Int32
 8   genres          4976 non-null   string
 9   averageRating   4976 non-null   float64
 10  numVotes        4976 non-null   int64
dtypes: Int32(4), float64(1), int64(1), object(2), string(3)
memory usage: 369.4+ KB

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

---

<a id="section2"></a>
## 2. Acquiring Data from The Movie Database (TMDb)

*The Movie Database ([TMDb](https://www.themoviedb.org))* is an alternative to IMDb that exposes a well-documented REST API. We use it to enrich the `df_movies` set with fields IMDb doesn't expose (plot, budget, revenue, cast, crew).

TMDb requires authentication. After registering an account, follow the [API setup docs](https://developers.themoviedb.org/3/getting-started/introduction) to obtain a *v3 API Read Token* and assign it to `token` below (or set the `TMDB_TOKEN` environment variable).

In [54]:
token = 'b92f861387d23f89b6036503f59fc4c4'

The TMDb API base URL is `https://api.themoviedb.org/3/`. The [documentation](https://developers.themoviedb.org/3/getting-started/introduction) lists every endpoint and offers a try-it-out sandbox with code snippets in multiple languages. The generated Python snippets come in two flavors — one using the standard library's `http.client`, the other using `requests`. We use `requests` throughout.

In [31]:
df_movies.set_index('tconst',inplace=True)

KeyError: "None of ['tconst'] are in the columns"

In [32]:
df_movies.head()

,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
tconst,,,,,,,,,,
tt0000417,short,A Trip to the Moon,Le voyage dans la lune,0,1902,<NA>,13,"Action,Adventure,Comedy",8.1,57200
tt0010323,movie,The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,0,1920,<NA>,67,"Horror,Mystery,Thriller",8.0,71863
tt0012349,movie,The Kid,The Kid,0,1921,<NA>,68,"Comedy,Drama,Family",8.2,137619
tt0013442,movie,Nosferatu: A Symphony of Horror,"Nosferatu, eine Symphonie des Grauens",0,1922,<NA>,94,"Fantasy,Horror",7.8,108889
tt0015324,movie,Sherlock Jr.,Sherlock Jr.,0,1924,<NA>,45,"Action,Comedy,Romance",8.2,58967

All examples in this section use the movie with IMDb ID `'tt0068646'` — *The Godfather*.

In [6]:
tgf_movie_id = 'tt0068646'
df_movies.loc[tgf_movie_id]

titleType                 movie
primaryTitle      The Godfather
originalTitle     The Godfather
isAdult                       0
startYear                  1972
endYear                    <NA>
runtimeMinutes              175
genres              Crime,Drama
averageRating               9.2
numVotes                2063067
Name: tt0068646, dtype: object

In [6]:
import requests
url = "https://api.themoviedb.org/3/movie/tt0068646?external_source=imdb_id&language=en_US"
response = requests.get(url, headers=headers)
tgf_data = response.json()

# Pretty-print JSON payload for readability
print(json.dumps(tgf_data, indent=3))

{
   "adult": false,
   "backdrop_path": "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
   "belongs_to_collection": {
      "id": 230,
      "name": "The Godfather Collection",
      "poster_path": "/zqV8MGXfpLZiFVObLxpAI7wWonJ.jpg",
      "backdrop_path": "/mDMCET9Ens5ANvZAWRpluBsMAtS.jpg"
   },
   "budget": 6000000,
   "genres": [
      {
         "id": 18,
         "name": "Drama"
      },
      {
         "id": 80,
         "name": "Crime"
      }
   ],
   "homepage": "http://www.thegodfather.com/",
   "id": 238,
   "imdb_id": "tt0068646",
   "origin_country": [
      "US"
   ],
   "original_language": "en",
   "original_title": "The Godfather",
   "overview": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
   "popularity": 165.902,
   "poster_path": "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
   "production_companies": [
      {
         "id": 4,
         "logo_path": "/gz66EfNoYPqHTYI4q9UEN4CbHRc.png",
         "name": "Paramount Pictures",
         "origin_country": "US"
      },
      {
         "id": 10211,
         "logo_path": null,
         "name": "Alfran Productions",
         "origin_country": "US"
      }
   ],
   "production_countries": [
      {
         "iso_3166_1": "US",
         "name": "United States of America"
      }
   ],
   "release_date": "1972-03-14",
   "revenue": 245066411,
   "runtime": 175,
   "spoken_languages": [
      {
         "english_name": "English",
         "iso_639_1": "en",
         "name": "English"
      },
      {
         "english_name": "Italian",
         "iso_639_1": "it",
         "name": "Italiano"
      },
      {
         "english_name": "Latin",
         "iso_639_1": "la",
         "name": "Latin"
      }
   ],
   "status": "Released",
   "tagline": "An offer you can't refuse.",
   "title": "The Godfather",
   "video": false,
   "vote_average": 8.688,
   "vote_count": 20969
}

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

<a id="section21"></a>
### 2.1 Fetching Movie Information

`GET /movie/{movie_id}` returns metadata for a single movie. `movie_id` can be either TMDb's native identifier or an `imdb_id` (which we pass via `external_source=imdb_id`). We also force English responses with `language=en_US`.

In [3]:
import requests
import json

url = "https://api.themoviedb.org/3/movie/tt0068646?external_source=imdb_id&language=en_US"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiOTJmODYxMzg3ZDIzZjg5YjYwMzY1MDNmNTlmYzRjNCIsIm5iZiI6MTczODMyMDQxMS40MDMsInN1YiI6IjY3OWNhYTFiNGU5YTQ1OTVlY2JkZTVmOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.sMFKBYBnQukD66tQPOYGIL_Xd3XBwWHZb2nQyYNvt_g"
}

In [17]:
tgf_data =

'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.'

Fetch and display the data for *The Godfather* (IMDb ID stored in `tgf_movie_id`).

In [135]:

response = requests.get(url, headers=headers)
tgf_data = response.json()

# Pretty-print JSON payload for readability
print(json.dumps(tgf_data, indent=3))

{
   "adult": false,
   "backdrop_path": "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
   "belongs_to_collection": {
      "id": 230,
      "name": "The Godfather Collection",
      "poster_path": "/zqV8MGXfpLZiFVObLxpAI7wWonJ.jpg",
      "backdrop_path": "/mDMCET9Ens5ANvZAWRpluBsMAtS.jpg"
   },
   "budget": 6000000,
   "genres": [
      {
         "id": 18,
         "name": "Drama"
      },
      {
         "id": 80,
         "name": "Crime"
      }
   ],
   "homepage": "http://www.thegodfather.com/",
   "id": 238,
   "imdb_id": "tt0068646",
   "origin_country": [
      "US"
   ],
   "original_language": "en",
   "original_title": "The Godfather",
   "overview": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
   "popularity": 179.703,
   "poster_path": "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
   "production_companies": [
      {
         "id": 4,
         "logo_path": "/gz66EfNoYPqHTYI4q9UEN4CbHRc.png",
         "name": "Paramount Pictures",
         "origin_country": "US"
      },
      {
         "id": 10211,
         "logo_path": null,
         "name": "Alfran Productions",
         "origin_country": "US"
      }
   ],
   "production_countries": [
      {
         "iso_3166_1": "US",
         "name": "United States of America"
      }
   ],
   "release_date": "1972-03-14",
   "revenue": 245066411,
   "runtime": 175,
   "spoken_languages": [
      {
         "english_name": "English",
         "iso_639_1": "en",
         "name": "English"
      },
      {
         "english_name": "Italian",
         "iso_639_1": "it",
         "name": "Italiano"
      },
      {
         "english_name": "Latin",
         "iso_639_1": "la",
         "name": "Latin"
      }
   ],
   "status": "Released",
   "tagline": "An offer you can't refuse.",
   "title": "The Godfather",
   "video": false,
   "vote_average": 8.7,
   "vote_count": 20954
}

In [138]:
tgf_data.keys()

dict_keys(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id', 'imdb_id', 'origin_country', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count'])

<div class="alert alert-block alert-warning">
<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
Each movie is identified by two fields: `id` (TMDb native) and `imdb_id`. This dual identity is a common source of bugs, so downstream we standardize on `imdb_id` across all stores.
</div>

Display the `overview` field — it holds the movie's plot summary.

In [139]:
print(tgf_data['overview'])

Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.

The `poster_path` field provides a relative URL that can be fetched at various sizes (e.g. `http://image.tmdb.org/t/p/w185/<poster_path>`).

In [140]:
Image = 'http://image.tmdb.org/t/p/w185'+tgf_data['poster_path']
Image

'http://image.tmdb.org/t/p/w185/3bhkrj58Vtu7enYsRolD1fZdja1.jpg'

Fetch metadata for every movie in `df_movies` and store it in a dictionary `movies_data` keyed by IMDb ID.

<div class="alert alert-block alert-danger">
<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
Each call takes ~0.5 seconds, so a sequential pull over ~4,000 movies is roughly 35 minutes. To make the notebook re-runnable without repeating the downloads, the results are cached to `data/backup/movie_data.json` and only re-downloaded if that file is absent. Error responses from the API still return JSON, so we gate every store on `response.status_code == 200`.
</div>

In [27]:
import os
x = 0
# If no local cache exists, download from API and persist
if not os.path.isfile('data/backup/movie_data.json'):
    # Fetch one movie at a time
    movie_data = { }
    for movie_id in df_movies.index:
        url = f"https://api.themoviedb.org/3/movie/{movie_id}?external_source=imdb_id&language=en_US"
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            movies_data[movie_id] = response.json()
            print(x)
            x += 1
            continue
            
       
        
    # Persist movie_data to JSON cache
    with open('data/backup/movie_data.json',"w") as movie_data_file:
         json.dump(movies_data, movie_data_file, indent=4, ensure_ascii=False) 
        
# Cache exists — load from disk 
else:
    with open('data/backup/movie_data.json','r') as movie_data_file:
        movie_data = json.load(movie_data_file) 
    
    
print(f"Number of movies fetched: {len(movie_data)}")

El de títulos obtenidos es 4295

Show the title and release date for the example movie, this time reading from the cached dictionary.

In [71]:
tgf_data = movies_data['tt0068646']
tgf_data['movie_results'][0]['title'], tgf_data['movie_results'][0]['release_date'],

('The Godfather', '1972-03-14')

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

<a id="section22"></a>
### 2.2 MongoDB Storage

NoSQL databases come in many flavors. MongoDB organizes data into collections of JSON-like documents — a natural fit for the TMDb JSON responses we just fetched.

MongoDB is available as a local install, but the easiest path is [MongoDB Atlas](https://www.mongodb.com/cloud/atlas), which offers a free-tier cloud cluster. The `pymongo` Python driver handles the client side.

Create a database named `dbmovies` with a collection `movies` (this can be done from the Atlas web console), then connect to it and store the client reference in `dbmovies`.

<div class="alert alert-block alert-danger">
<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
On some systems the client throws a TLS error on connect. The fix is to install `certifi` and pass `tlsCAFile=certifi.where()` when constructing `MongoClient`.
</div>

In [4]:
!pip install "pymongo[srv]"

Collecting pymongo[srv]
  Downloading pymongo-4.11-cp312-cp312-win_amd64.whl.metadata (22 kB)
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo[srv])
  Downloading dnspython-2.7.0-py3-none-any.whl.metadata (5.8 kB)
Downloading dnspython-2.7.0-py3-none-any.whl (313 kB)
Downloading pymongo-4.11-cp312-cp312-win_amd64.whl (882 kB)
   ---------------------------------------- 0.0/882.3 kB ? eta -:--:--
   --------------------------------------- 882.3/882.3 kB 13.2 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.7.0 pymongo-4.11

WARNING: pymongo 4.11 does not provide the extra 'srv'

In [5]:
import certifi
from pymongo import MongoClient

In [6]:
import urllib.parse
password = urllib.parse.quote_plus("Polinya1@")  # This encodes the special character (@)
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = f"mongodb+srv://lun3429:{password}@cluster0.slflo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

Insert `movies_data` into `dbmovies.movies` with `insert_many()`. Collections hold sequences of documents (not dictionaries), so we pass `movies_data.values()`. We don't lose the key because every document contains `imdb_id`.

For robustness across re-runs, drop the collection first (`.drop()`) and re-insert from scratch. Terminate the final statement with `;` to avoid the noisy return value.

In [7]:
dbmovies = client["dbmovies"]

In [36]:
dbmovies = client["dbmovies"]  
collection = dbmovies["movies"]  
collection.drop()

with open("data/backup/movie_data.json", "r", encoding="utf-8") as file:
    movie_data = json.load(file)  

movies_list = list(movie_data.values())

collection.drop()

insert_result = collection.insert_many(movies_list)

print(f"Inserted {len(insert_result.inserted_ids)} documents into MongoDB")

Inserted 4295 documents into MongoDB

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

<a id="section23"></a>
### 2.3 Downloading Credits

Credits describe the people involved in a film — cast, director, writer, and so on. `GET /movie/{movie_id}/credits` returns the credits for a single movie.

Fetch and display the credits for *The Godfather*.

In [13]:
url = f"https://api.themoviedb.org/3/movie/tt0068646/credits"
response = requests.get(url, headers=headers)
tgf_data = response.json()
print(json.dumps(tgf_data,indent=3))

{
   "id": 238,
   "cast": [
      {
         "adult": false,
         "gender": 2,
         "id": 3084,
         "known_for_department": "Acting",
         "name": "Marlon Brando",
         "original_name": "Marlon Brando",
         "popularity": 27.275,
         "profile_path": "/fuTEPMsBtV1zE98ujPONbKiYDc2.jpg",
         "cast_id": 146,
         "character": "Don Vito Corleone",
         "credit_id": "6489aa85e2726001072483a9",
         "order": 0
      },
      {
         "adult": false,
         "gender": 2,
         "id": 1158,
         "known_for_department": "Acting",
         "name": "Al Pacino",
         "original_name": "Al Pacino",
         "popularity": 50.623,
         "profile_path": "/fMDFeVf0pjopTJbyRSLFwNDm8Wr.jpg",
         "cast_id": 147,
         "character": "Michael Corleone",
         "credit_id": "6489aa936f8d9500afdf219c",
         "order": 1
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3085,
         "known_for_department": "Acting",
         "name": "James Caan",
         "original_name": "James Caan",
         "popularity": 32.077,
         "profile_path": "/v3flJtQEyczxENi29yJyvnN6LVt.jpg",
         "cast_id": 148,
         "character": "Sonny Corleone",
         "credit_id": "6489aabc99259c00ff111136",
         "order": 2
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3087,
         "known_for_department": "Acting",
         "name": "Robert Duvall",
         "original_name": "Robert Duvall",
         "popularity": 31.486,
         "profile_path": "/ybMmK25h4IVtfE7qrnlVp47RQlh.jpg",
         "cast_id": 149,
         "character": "Tom Hagen",
         "credit_id": "6489aace99259c011c42808d",
         "order": 3
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3086,
         "known_for_department": "Acting",
         "name": "Richard S. Castellano",
         "original_name": "Richard S. Castellano",
         "popularity": 9.036,
         "profile_path": "/1vr75BdHWret81vuSJ3ugiCBkxw.jpg",
         "cast_id": 150,
         "character": "Clemenza",
         "credit_id": "6489aaf86f8d9500c88bea14",
         "order": 4
      },
      {
         "adult": false,
         "gender": 1,
         "id": 3092,
         "known_for_department": "Acting",
         "name": "Diane Keaton",
         "original_name": "Diane Keaton",
         "popularity": 29.051,
         "profile_path": "/tnx7pJqisfAzvXOR5wHQsbnH9XH.jpg",
         "cast_id": 151,
         "character": "Kay Adams",
         "credit_id": "6489ab23bf31f25055a33a46",
         "order": 5
      },
      {
         "adult": false,
         "gender": 1,
         "id": 3094,
         "known_for_department": "Acting",
         "name": "Talia Shire",
         "original_name": "Talia Shire",
         "popularity": 18.656,
         "profile_path": "/xvJ47wKL5zpwFXFFNZQmFmf7i9F.jpg",
         "cast_id": 152,
         "character": "Connie Corleone Rizzi",
         "credit_id": "6489ab5799259c011c4280d8",
         "order": 6
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3095,
         "known_for_department": "Acting",
         "name": "Gianni Russo",
         "original_name": "Gianni Russo",
         "popularity": 6.175,
         "profile_path": "/jfeGnQfXMzKXsuSPm9oTxm6FOuz.jpg",
         "cast_id": 153,
         "character": "Carlo Rizzi",
         "credit_id": "6489ab77e375c00139c26e5b",
         "order": 7
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3088,
         "known_for_department": "Acting",
         "name": "Sterling Hayden",
         "original_name": "Sterling Hayden",
         "popularity": 12.456,
         "profile_path": "/eRKaKeHjMKjNPOuENLccfVuyfVm.jpg",
         "cast_id": 154,
         "character": "Captain McCluskey",
         "credit_id": "6489abe0d2b209014e0b8df9",
         "order": 8
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3142,
         "known_for_department": "Acting",
         "name": "John Marley",
         "original_name": "John Marley",
         "popularity": 8.671,
         "profile_path": "/xyzwd0CiBjXfowH3HcPhvuWcV5B.jpg",
         "cast_id": 155,
         "character": "Jack Woltz",
         "credit_id": "6489ac0299259c011c42811f",
         "order": 9
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3090,
         "known_for_department": "Acting",
         "name": "Richard Conte",
         "original_name": "Richard Conte",
         "popularity": 6.651,
         "profile_path": "/bDegodf4dYGXMejdm4T6XgOJwlr.jpg",
         "cast_id": 156,
         "character": "Barzini",
         "credit_id": "6489ac126f8d9500afdf2251",
         "order": 10
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3091,
         "known_for_department": "Acting",
         "name": "Al Lettieri",
         "original_name": "Al Lettieri",
         "popularity": 13.308,
         "profile_path": "/fE5mEWPkkVJlCji0EoKht8PYw89.jpg",
         "cast_id": 157,
         "character": "Sollozzo",
         "credit_id": "6489ac20e375c000acc796d1",
         "order": 11
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3093,
         "known_for_department": "Acting",
         "name": "Abe Vigoda",
         "original_name": "Abe Vigoda",
         "popularity": 14.185,
         "profile_path": "/luWKPNb58IgJ2ovrtgPAzHGLLYL.jpg",
         "cast_id": 158,
         "character": "Sal Tessio",
         "credit_id": "6489ac2dbf31f2505708a65c",
         "order": 12
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3096,
         "known_for_department": "Acting",
         "name": "John Cazale",
         "original_name": "John Cazale",
         "popularity": 4.974,
         "profile_path": "/7uKBc2BVbLlAiHuSdfioe1OUnCX.jpg",
         "cast_id": 159,
         "character": "Fredo Corleone",
         "credit_id": "6489ac3a6f8d9500afdf2260",
         "order": 13
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3143,
         "known_for_department": "Acting",
         "name": "Rudy Bond",
         "original_name": "Rudy Bond",
         "popularity": 8.601,
         "profile_path": "/plsYnzwNlwGWc4s5YT1NASj4YvN.jpg",
         "cast_id": 160,
         "character": "Cuneo",
         "credit_id": "6489ac5de375c00139c26eb2",
         "order": 14
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3144,
         "known_for_department": "Acting",
         "name": "Al Martino",
         "original_name": "Al Martino",
         "popularity": 4.61,
         "profile_path": "/jrxnZxAOBVXZaDr9r0nYpMnQwiU.jpg",
         "cast_id": 161,
         "character": "Johnny Fontane",
         "credit_id": "6489ac7199259c01392da0db",
         "order": 15
      },
      {
         "adult": false,
         "gender": 1,
         "id": 933716,
         "known_for_department": "Acting",
         "name": "Morgana King",
         "original_name": "Morgana King",
         "popularity": 2.937,
         "profile_path": "/1zzGZpZqedECtHMwfFIqd51nncM.jpg",
         "cast_id": 162,
         "character": "Mama Corleone",
         "credit_id": "6489ac82e272600107248470",
         "order": 16
      },
      {
         "adult": false,
         "gender": 2,
         "id": 106811,
         "known_for_department": "Acting",
         "name": "Lenny Montana",
         "original_name": "Lenny Montana",
         "popularity": 3.837,
         "profile_path": "/3R52Zh3MBCaSPqmcyWcD1Y0N4wo.jpg",
         "cast_id": 163,
         "character": "Luca Brasi",
         "credit_id": "6489ac90d2b20900ca220c08",
         "order": 17
      },
      {
         "adult": false,
         "gender": 2,
         "id": 99724,
         "known_for_department": "Acting",
         "name": "John Martino",
         "original_name": "John Martino",
         "popularity": 4.803,
         "profile_path": "/3c8BOgJ8UdHi5x5BS3lYnFngxB5.jpg",
         "cast_id": 164,
         "character": "Paulie Gatto",
         "credit_id": "6489ac9dd2b20900ca220c0f",
         "order": 18
      },
      {
         "adult": false,
         "gender": 2,
         "id": 1195877,
         "known_for_department": "Acting",
         "name": "Salvatore Corsitto",
         "original_name": "Salvatore Corsitto",
         "popularity": 3.077,
         "profile_path": "/79OfgwtdP5qsR1UX6ERkrdmRT8c.jpg",
         "cast_id": 165,
         "character": "Bonasera",
         "credit_id": "6489acaae375c000acc79705",
         "order": 19
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3174,
         "known_for_department": "Acting",
         "name": "Richard Bright",
         "original_name": "Richard Bright",
         "popularity": 7.38,
         "profile_path": "/potMaJ2u5PRjXZb7qF9lSW1ldNZ.jpg",
         "cast_id": 166,
         "character": "Neri",
         "credit_id": "6489acc2bf31f25054b828e4",
         "order": 20
      },
      {
         "adult": false,
         "gender": 2,
         "id": 20752,
         "known_for_department": "Acting",
         "name": "Alex Rocco",
         "original_name": "Alex Rocco",
         "popularity": 12.315,
         "profile_path": "/uAG4qvYhYHuCyyXGm3lqC4o6ujc.jpg",
         "cast_id": 167,
         "character": "Moe Greene",
         "credit_id": "6489acd1d2b20900ad3ec8cf",
         "order": 21
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3414,
         "known_for_department": "Acting",
         "name": "Tony Giorgio",
         "original_name": "Tony Giorgio",
         "popularity": 8.26,
         "profile_path": "/1uhgwgjoX7WaakEOBmtBRJKtgEB.jpg",
         "cast_id": 168,
         "character": "Bruno Tattaglia",
         "credit_id": "6489ad08bf31f25055a33b08",
         "order": 22
      },
      {
         "adult": false,
         "gender": 2,
         "id": 82779,
         "known_for_department": "Acting",
         "name": "Vito Scotti",
         "original_name": "Vito Scotti",
         "popularity": 8.749,
         "profile_path": "/vZJVyk2k8yCqLbpG4b9R22IYjSO.jpg",
         "cast_id": 169,
         "character": "Nazorine",
         "credit_id": "6489ad166f8d9501023e6cb2",
         "order": 23
      },
      {
         "adult": false,
         "gender": 1,
         "id": 982089,
         "known_for_department": "Acting",
         "name": "Tere Livrano",
         "original_name": "Tere Livrano",
         "popularity": 2.689,
         "profile_path": "/mSBI5B8t5WdA1vY82YlcySTopam.jpg",
         "cast_id": 170,
         "character": "Theresa Hagen",
         "credit_id": "6489ad23d2b20900ad3ec8f9",
         "order": 24
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3413,
         "known_for_department": "Acting",
         "name": "Victor Rendina",
         "original_name": "Victor Rendina",
         "popularity": 4.935,
         "profile_path": "/vuNdsjDpgom80WBdB2WBTWuEIuM.jpg",
         "cast_id": 171,
         "character": "Philip Tattaglia",
         "credit_id": "6489ad306f8d9500c88beb2c",
         "order": 25
      },
      {
         "adult": false,
         "gender": 1,
         "id": 167363,
         "known_for_department": "Acting",
         "name": "Jeannie Linero",
         "original_name": "Jeannie Linero",
         "popularity": 1.971,
         "profile_path": null,
         "cast_id": 172,
         "character": "Lucy Mancini",
         "credit_id": "6489ad4f6f8d95011f2439db",
         "order": 26
      },
      {
         "adult": false,
         "gender": 1,
         "id": 160728,
         "known_for_department": "Acting",
         "name": "Julie Gregg",
         "original_name": "Julie Gregg",
         "popularity": 13.321,
         "profile_path": "/8Kx71BnZNtpzb86jH7fcArWhJBh.jpg",
         "cast_id": 173,
         "character": "Sandra Corleone",
         "credit_id": "6489ad696f8d9500c88beb4e",
         "order": 27
      },
      {
         "adult": false,
         "gender": 1,
         "id": 4111331,
         "known_for_department": "Acting",
         "name": "Ardell Sheridan",
         "original_name": "Ardell Sheridan",
         "popularity": 1.134,
         "profile_path": null,
         "cast_id": 174,
         "character": "Mrs. Clemenza",
         "credit_id": "6489adb8bf31f25054b8295f",
         "order": 28
      },
      {
         "adult": false,
         "gender": 1,
         "id": 3145,
         "known_for_department": "Acting",
         "name": "Simonetta Stefanelli",
         "original_name": "Simonetta Stefanelli",
         "popularity": 20.65,
         "profile_path": "/sVDrhgxuE6SHnj7q07OG6ywPUYR.jpg",
         "cast_id": 175,
         "character": "Apollonia - Sicilian Sequence",
         "credit_id": "6489ae04bf31f25055a33b87",
         "order": 29
      },
      {
         "adult": false,
         "gender": 2,
         "id": 27647,
         "known_for_department": "Acting",
         "name": "Angelo Infanti",
         "original_name": "Angelo Infanti",
         "popularity": 4.038,
         "profile_path": "/dkRVpiDj9YyiuM15XZKT11zZBIR.jpg",
         "cast_id": 176,
         "character": "Fabrizio - Sicilian Sequence",
         "credit_id": "6489ae14d2b20900ca220cca",
         "order": 30
      },
      {
         "adult": false,
         "gender": 2,
         "id": 24604,
         "known_for_department": "Acting",
         "name": "Corrado Gaipa",
         "original_name": "Corrado Gaipa",
         "popularity": 2.938,
         "profile_path": "/7vR2BOdVw9FwJKjgpcisjKEytnL.jpg",
         "cast_id": 177,
         "character": "Don Tommasino - Sicilian Sequence",
         "credit_id": "6489ae21d2b20900ca220cd4",
         "order": 31
      },
      {
         "adult": false,
         "gender": 2,
         "id": 44860,
         "known_for_department": "Acting",
         "name": "Franco Citti",
         "original_name": "Franco Citti",
         "popularity": 4.593,
         "profile_path": "/mttQPjOHaql4RKsfYriUA7HuROE.jpg",
         "cast_id": 178,
         "character": "Calo - Sicilian Sequence",
         "credit_id": "6489ae2e6f8d9500c88bebcf",
         "order": 32
      },
      {
         "adult": false,
         "gender": 2,
         "id": 119431,
         "known_for_department": "Acting",
         "name": "Saro Urz\u00ec",
         "original_name": "Saro Urz\u00ec",
         "popularity": 3.126,
         "profile_path": "/wp88yz8T1TJcw5egiDu1m5a302D.jpg",
         "cast_id": 179,
         "character": "Vitelli - Sicilian Sequence",
         "credit_id": "6489ae3ce2726000afc4c253",
         "order": 33
      },
      {
         "adult": false,
         "gender": 2,
         "id": 38803,
         "known_for_department": "Writing",
         "name": "Roman Coppola",
         "original_name": "Roman Coppola",
         "popularity": 8.67,
         "profile_path": "/dq454EhrDVKBsiYzuLr0IkKa18v.jpg",
         "cast_id": 182,
         "character": "Boy on Street Who Attended Funeral (uncredited)",
         "credit_id": "6489af3ce2726001287c0ab0",
         "order": 34
      },
      {
         "adult": false,
         "gender": 1,
         "id": 1769,
         "known_for_department": "Directing",
         "name": "Sofia Coppola",
         "original_name": "Sofia Coppola",
         "popularity": 13.055,
         "profile_path": "/dzHC2LxmarkBxWLhjp2DRa5oCev.jpg",
         "cast_id": 181,
         "character": "Michael Francis Rizzi (uncredited)",
         "credit_id": "6489af2de375c000acc797fe",
         "order": 35
      },
      {
         "adult": false,
         "gender": 0,
         "id": 1209294,
         "known_for_department": "Acting",
         "name": "Don Costello",
         "original_name": "Don Costello",
         "popularity": 1.427,
         "profile_path": null,
         "cast_id": 183,
         "character": "Don Victor Stracci (uncredited)",
         "credit_id": "6489af7abf31f2505883d309",
         "order": 36
      },
      {
         "adult": false,
         "gender": 1,
         "id": 126072,
         "known_for_department": "Acting",
         "name": "Italia Coppola",
         "original_name": "Italia Coppola",
         "popularity": 1.721,
         "profile_path": null,
         "cast_id": 184,
         "character": "Extra in Wedding Scene (uncredited)",
         "credit_id": "6489afb46f8d95011f243b21",
         "order": 37
      },
      {
         "adult": false,
         "gender": 2,
         "id": 2870,
         "known_for_department": "Production",
         "name": "Gray Frederickson",
         "original_name": "Gray Frederickson",
         "popularity": 2.163,
         "profile_path": null,
         "cast_id": 195,
         "character": "Cowboy on the Set at Woltz's Studio (uncredited)",
         "credit_id": "6489b195e375c00139c270d3",
         "order": 38
      },
      {
         "adult": false,
         "gender": 2,
         "id": 160621,
         "known_for_department": "Acting",
         "name": "Ron Gilbert",
         "original_name": "Ron Gilbert",
         "popularity": 5.503,
         "profile_path": "/qrY6w2k0YpuMB2yTCOv6cxeQtmw.jpg",
         "cast_id": 185,
         "character": "Usher in Bridal Party (uncredited)",
         "credit_id": "6489afe46f8d95013c752d10",
         "order": 39
      },
      {
         "adult": false,
         "gender": 2,
         "id": 1233541,
         "known_for_department": "Acting",
         "name": "Sonny Grosso",
         "original_name": "Sonny Grosso",
         "popularity": 1.741,
         "profile_path": null,
         "cast_id": 202,
         "character": "Cop Outside Hospital (uncredited)",
         "credit_id": "6489b33fe272600107248730",
         "order": 40
      },
      {
         "adult": false,
         "gender": 2,
         "id": 20973,
         "known_for_department": "Acting",
         "name": "Louis Guss",
         "original_name": "Louis Guss",
         "popularity": 3.713,
         "profile_path": "/hz5Akuh4QcqitlifYwDiZ9ut6Tr.jpg",
         "cast_id": 180,
         "character": "Don Zaluchi (uncredited)",
         "credit_id": "6489af11e375c000ff4ab5f2",
         "order": 41
      },
      {
         "adult": false,
         "gender": 2,
         "id": 1068099,
         "known_for_department": "Acting",
         "name": "Randy Jurgensen",
         "original_name": "Randy Jurgensen",
         "popularity": 1.572,
         "profile_path": "/xRoN79wRLndTMCJoaBSsdjQVIzI.jpg",
         "cast_id": 186,
         "character": "Sonny's Killer #1 (uncredited)",
         "credit_id": "6489affed2b209014e0b8fdb",
         "order": 42
      },
      {
         "adult": false,
         "gender": 2,
         "id": 55672,
         "known_for_department": "Acting",
         "name": "Tony King",
         "original_name": "Tony King",
         "popularity": 2.52,
         "profile_path": "/hOVVHEyc6euuuRhCLo6Q5YE4lLz.jpg",
         "cast_id": 196,
         "character": "Tony - Stablehand (uncredited)",
         "credit_id": "6489b214e375c000ff4ab714",
         "order": 43
      },
      {
         "adult": false,
         "gender": 2,
         "id": 61241,
         "known_for_department": "Acting",
         "name": "Tony Lip",
         "original_name": "Tony Lip",
         "popularity": 5.587,
         "profile_path": "/6xz6XmjgiCCOm067OzWYziD4Mxa.jpg",
         "cast_id": 206,
         "character": "Wedding Guest (uncredited)",
         "credit_id": "6489b6276f8d9500e5015933",
         "order": 44
      },
      {
         "adult": false,
         "gender": 2,
         "id": 1503036,
         "known_for_department": "Acting",
         "name": "Joe Lo Grippo",
         "original_name": "Joe Lo Grippo",
         "popularity": 2.113,
         "profile_path": null,
         "cast_id": 188,
         "character": "Sonny's Bodyguard (uncredited)",
         "credit_id": "6489b0736f8d9500afdf2448",
         "order": 45
      },
      {
         "adult": false,
         "gender": 2,

We explore the JSON structure one level at a time, starting from the top-level dictionary keys.

In [14]:
tgf_data.keys()

dict_keys(['id', 'cast', 'crew'])

The JSON has three top-level fields per movie:

* `id` — TMDb's native identifier
* `crew` — production crew
* `cast` — acting cast

We process `crew` and `cast` separately.

#### Director (crew)

`crew` is a list of dictionaries, one per crew member. The next cell previews the first three entries.

In [15]:
tgf_data['crew'][0:3]

[{'adult': False,
  'gender': 2,
  'id': 457,
  'known_for_department': 'Production',
  'name': 'Albert S. Ruddy',
  'original_name': 'Albert S. Ruddy',
  'popularity': 3.828,
  'profile_path': '/jSkLkR79OmqYHg0kx4WWXI1TYPP.jpg',
  'credit_id': '52fe422bc3a36847f80093cf',
  'department': 'Production',
  'job': 'Producer'},
 {'adult': False,
  'gender': 2,
  'id': 3083,
  'known_for_department': 'Writing',
  'name': 'Mario Puzo',
  'original_name': 'Mario Puzo',
  'popularity': 6.928,
  'profile_path': '/lEsT1uCZAZg1nYDQe3Fsj9CalzT.jpg',
  'credit_id': '52fe422bc3a36847f80093d5',
  'department': 'Writing',
  'job': 'Screenplay'},
 {'adult': False,
  'gender': 2,
  'id': 1776,
  'known_for_department': 'Directing',
  'name': 'Francis Ford Coppola',
  'original_name': 'Francis Ford Coppola',
  'popularity': 18.88,
  'profile_path': '/IwGgkmW6IoJ9vuNF0T9CU3FYUX.jpg',
  'credit_id': '52fe422bc3a36847f80093db',
  'department': 'Writing',
  'job': 'Screenplay'}]

From `tgf_data` (The Godfather's credits), extract the entries where `job == 'Director'` using `filter()`. The result is a list — usually of size one, but some films credit multiple directors.

In [16]:
director = list(filter(lambda p:p['job'] == 'Director',tgf_data['crew'] ))
print(director)

[{'adult': False, 'gender': 2, 'id': 1776, 'known_for_department': 'Directing', 'name': 'Francis Ford Coppola', 'original_name': 'Francis Ford Coppola', 'popularity': 18.88, 'profile_path': '/IwGgkmW6IoJ9vuNF0T9CU3FYUX.jpg', 'credit_id': '5e92505cccb15f00136de455', 'department': 'Directing', 'job': 'Director'}]

#### Cast

The third top-level field, `cast`, is a list of dictionaries — one per actor who appeared in the film. The next cell previews the first three entries.

In [18]:
tgf_data['cast'][0:3]

[{'adult': False,
  'gender': 2,
  'id': 3084,
  'known_for_department': 'Acting',
  'name': 'Marlon Brando',
  'original_name': 'Marlon Brando',
  'popularity': 27.275,
  'profile_path': '/fuTEPMsBtV1zE98ujPONbKiYDc2.jpg',
  'cast_id': 146,
  'character': 'Don Vito Corleone',
  'credit_id': '6489aa85e2726001072483a9',
  'order': 0},
 {'adult': False,
  'gender': 2,
  'id': 1158,
  'known_for_department': 'Acting',
  'name': 'Al Pacino',
  'original_name': 'Al Pacino',
  'popularity': 50.623,
  'profile_path': '/fMDFeVf0pjopTJbyRSLFwNDm8Wr.jpg',
  'cast_id': 147,
  'character': 'Michael Corleone',
  'credit_id': '6489aa936f8d9500afdf219c',
  'order': 1},
 {'adult': False,
  'gender': 2,
  'id': 3085,
  'known_for_department': 'Acting',
  'name': 'James Caan',
  'original_name': 'James Caan',
  'popularity': 32.077,
  'profile_path': '/v3flJtQEyczxENi29yJyvnN6LVt.jpg',
  'cast_id': 148,
  'character': 'Sonny Corleone',
  'credit_id': '6489aabc99259c00ff111136',
  'order': 2}]

The `order` field encodes billing rank. Though it often matches list position, we treat it as the source of truth and filter on it explicitly.

Extract the top three most-billed cast members (`order < 3`).

In [19]:
top_cast = list(filter(lambda p:p['order']<3,tgf_data['cast']))
top_cast

[{'adult': False,
  'gender': 2,
  'id': 3084,
  'known_for_department': 'Acting',
  'name': 'Marlon Brando',
  'original_name': 'Marlon Brando',
  'popularity': 27.275,
  'profile_path': '/fuTEPMsBtV1zE98ujPONbKiYDc2.jpg',
  'cast_id': 146,
  'character': 'Don Vito Corleone',
  'credit_id': '6489aa85e2726001072483a9',
  'order': 0},
 {'adult': False,
  'gender': 2,
  'id': 1158,
  'known_for_department': 'Acting',
  'name': 'Al Pacino',
  'original_name': 'Al Pacino',
  'popularity': 50.623,
  'profile_path': '/fMDFeVf0pjopTJbyRSLFwNDm8Wr.jpg',
  'cast_id': 147,
  'character': 'Michael Corleone',
  'credit_id': '6489aa936f8d9500afdf219c',
  'order': 1},
 {'adult': False,
  'gender': 2,
  'id': 3085,
  'known_for_department': 'Acting',
  'name': 'James Caan',
  'original_name': 'James Caan',
  'popularity': 32.077,
  'profile_path': '/v3flJtQEyczxENi29yJyvnN6LVt.jpg',
  'cast_id': 148,
  'character': 'Sonny Corleone',
  'credit_id': '6489aabc99259c00ff111136',
  'order': 2}]

<div class="alert alert-block alert-warning">
<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
Each person carries a TMDb-native `id`. For consistency we use `imdb_id` as the canonical identifier throughout.
</div>

#### Bulk download

For each movie in `movie_data`, fetch credits and persist each response directly into a `credits` collection in `dbmovies`. To keep identifiers consistent, replace the incoming `id` field with `imdb_id` before storing.

<div class="alert alert-block alert-danger">
<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
Before every API call, check whether the credits are already cached (`{'imdb_id': movie_id}` query). Only store when the response is OK (`response.status_code == 200`).
</div>

In [24]:
dbmovies.list_collections()

In [28]:
movie_data['tt0000417']

{'adult': False,
 'backdrop_path': '/g67r1eiQD3ERSEQFCFkSn7TeGw5.jpg',
 'belongs_to_collection': None,
 'budget': 5985,
 'genres': [{'id': 12, 'name': 'Adventure'},
  {'id': 878, 'name': 'Science Fiction'}],
 'homepage': '',
 'id': 775,
 'imdb_id': 'tt0000417',
 'origin_country': ['FR'],
 'original_language': 'fr',
 'original_title': 'Le Voyage dans la Lune',
 'overview': 'Professor Barbenfouillis and five of his colleagues from the Academy of Astronomy travel to the Moon aboard a rocket propelled by a giant cannon. Once on the lunar surface, the bold explorers face the many perils hidden in the caves of the mysterious planet.',
 'popularity': 16.679,
 'poster_path': '/9o0v5LLFk51nyTBHZSre6OB37n2.jpg',
 'production_companies': [{'id': 7159,
   'logo_path': None,
   'name': 'Star Film',
   'origin_country': 'FR'}],
 'production_countries': [{'iso_3166_1': 'FR', 'name': 'France'}],
 'release_date': '1902-06-21',
 'revenue': 0,
 'runtime': 15,
 'spoken_languages': [{'english_name': 'No Language',
   'iso_639_1': 'xx',
   'name': 'No Language'}],
 'status': 'Released',
 'tagline': '',
 'title': 'A Trip to the Moon',
 'video': False,
 'vote_average': 7.9,
 'vote_count': 1810}

In [38]:
movies_id = [movie_data['imdb_id'] for movie_data in movie_data.values()]
collection_credits = dbmovies['credits']

# query a la coleccion y genera una lista con los imdb_id
existing_ids = [doc["imdb_id"] for doc in collection_credits.find({}, {"imdb_id": 1, "_id": 0})]

#itera sobre los elementos de movies_id
for movie_id in movies_id:
    # comprueba que la movie_id to este ya en la coleccion
    if movie_id not in existing_ids:
        url = f"https://api.themoviedb.org/3/movie/{movie_id}/credits"
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            credits_movie = response.json()
            credits_movie["imdb_id"] = movie_id 
            del credits_movie["id"]  
            collection_credits.insert_one(credits_movie)  # Insert into MongoDB

In [4]:
#code to get movie credits
url = f"https://api.themoviedb.org/3/movie/tt0068646/credits"
response = requests.get(url, headers=headers)
tgf_data = response.json()
print(json.dumps(tgf_data,indent=3))

{
   "id": 238,
   "cast": [
      {
         "adult": false,
         "gender": 2,
         "id": 3084,
         "known_for_department": "Acting",
         "name": "Marlon Brando",
         "original_name": "Marlon Brando",
         "popularity": 24.583,
         "profile_path": "/fuTEPMsBtV1zE98ujPONbKiYDc2.jpg",
         "cast_id": 146,
         "character": "Don Vito Corleone",
         "credit_id": "6489aa85e2726001072483a9",
         "order": 0
      },
      {
         "adult": false,
         "gender": 2,
         "id": 1158,
         "known_for_department": "Acting",
         "name": "Al Pacino",
         "original_name": "Al Pacino",
         "popularity": 53.187,
         "profile_path": "/fMDFeVf0pjopTJbyRSLFwNDm8Wr.jpg",
         "cast_id": 147,
         "character": "Michael Corleone",
         "credit_id": "6489aa936f8d9500afdf219c",
         "order": 1
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3085,
         "known_for_department": "Acting",
         "name": "James Caan",
         "original_name": "James Caan",
         "popularity": 36.023,
         "profile_path": "/v3flJtQEyczxENi29yJyvnN6LVt.jpg",
         "cast_id": 148,
         "character": "Sonny Corleone",
         "credit_id": "6489aabc99259c00ff111136",
         "order": 2
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3087,
         "known_for_department": "Acting",
         "name": "Robert Duvall",
         "original_name": "Robert Duvall",
         "popularity": 38.646,
         "profile_path": "/ybMmK25h4IVtfE7qrnlVp47RQlh.jpg",
         "cast_id": 149,
         "character": "Tom Hagen",
         "credit_id": "6489aace99259c011c42808d",
         "order": 3
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3086,
         "known_for_department": "Acting",
         "name": "Richard S. Castellano",
         "original_name": "Richard S. Castellano",
         "popularity": 9.111,
         "profile_path": "/1vr75BdHWret81vuSJ3ugiCBkxw.jpg",
         "cast_id": 150,
         "character": "Clemenza",
         "credit_id": "6489aaf86f8d9500c88bea14",
         "order": 4
      },
      {
         "adult": false,
         "gender": 1,
         "id": 3092,
         "known_for_department": "Acting",
         "name": "Diane Keaton",
         "original_name": "Diane Keaton",
         "popularity": 40.671,
         "profile_path": "/tnx7pJqisfAzvXOR5wHQsbnH9XH.jpg",
         "cast_id": 151,
         "character": "Kay Adams",
         "credit_id": "6489ab23bf31f25055a33a46",
         "order": 5
      },
      {
         "adult": false,
         "gender": 1,
         "id": 3094,
         "known_for_department": "Acting",
         "name": "Talia Shire",
         "original_name": "Talia Shire",
         "popularity": 15.197,
         "profile_path": "/xvJ47wKL5zpwFXFFNZQmFmf7i9F.jpg",
         "cast_id": 152,
         "character": "Connie Corleone Rizzi",
         "credit_id": "6489ab5799259c011c4280d8",
         "order": 6
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3095,
         "known_for_department": "Acting",
         "name": "Gianni Russo",
         "original_name": "Gianni Russo",
         "popularity": 8.645,
         "profile_path": "/jfeGnQfXMzKXsuSPm9oTxm6FOuz.jpg",
         "cast_id": 153,
         "character": "Carlo Rizzi",
         "credit_id": "6489ab77e375c00139c26e5b",
         "order": 7
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3088,
         "known_for_department": "Acting",
         "name": "Sterling Hayden",
         "original_name": "Sterling Hayden",
         "popularity": 10.137,
         "profile_path": "/eRKaKeHjMKjNPOuENLccfVuyfVm.jpg",
         "cast_id": 154,
         "character": "Captain McCluskey",
         "credit_id": "6489abe0d2b209014e0b8df9",
         "order": 8
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3142,
         "known_for_department": "Acting",
         "name": "John Marley",
         "original_name": "John Marley",
         "popularity": 11.801,
         "profile_path": "/xyzwd0CiBjXfowH3HcPhvuWcV5B.jpg",
         "cast_id": 155,
         "character": "Jack Woltz",
         "credit_id": "6489ac0299259c011c42811f",
         "order": 9
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3090,
         "known_for_department": "Acting",
         "name": "Richard Conte",
         "original_name": "Richard Conte",
         "popularity": 9.311,
         "profile_path": "/bDegodf4dYGXMejdm4T6XgOJwlr.jpg",
         "cast_id": 156,
         "character": "Barzini",
         "credit_id": "6489ac126f8d9500afdf2251",
         "order": 10
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3091,
         "known_for_department": "Acting",
         "name": "Al Lettieri",
         "original_name": "Al Lettieri",
         "popularity": 8.792,
         "profile_path": "/fE5mEWPkkVJlCji0EoKht8PYw89.jpg",
         "cast_id": 157,
         "character": "Sollozzo",
         "credit_id": "6489ac20e375c000acc796d1",
         "order": 11
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3093,
         "known_for_department": "Acting",
         "name": "Abe Vigoda",
         "original_name": "Abe Vigoda",
         "popularity": 15.456,
         "profile_path": "/luWKPNb58IgJ2ovrtgPAzHGLLYL.jpg",
         "cast_id": 158,
         "character": "Sal Tessio",
         "credit_id": "6489ac2dbf31f2505708a65c",
         "order": 12
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3096,
         "known_for_department": "Acting",
         "name": "John Cazale",
         "original_name": "John Cazale",
         "popularity": 6.292,
         "profile_path": "/7uKBc2BVbLlAiHuSdfioe1OUnCX.jpg",
         "cast_id": 159,
         "character": "Fredo Corleone",
         "credit_id": "6489ac3a6f8d9500afdf2260",
         "order": 13
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3143,
         "known_for_department": "Acting",
         "name": "Rudy Bond",
         "original_name": "Rudy Bond",
         "popularity": 9.78,
         "profile_path": "/plsYnzwNlwGWc4s5YT1NASj4YvN.jpg",
         "cast_id": 160,
         "character": "Cuneo",
         "credit_id": "6489ac5de375c00139c26eb2",
         "order": 14
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3144,
         "known_for_department": "Acting",
         "name": "Al Martino",
         "original_name": "Al Martino",
         "popularity": 4.583,
         "profile_path": "/jrxnZxAOBVXZaDr9r0nYpMnQwiU.jpg",
         "cast_id": 161,
         "character": "Johnny Fontane",
         "credit_id": "6489ac7199259c01392da0db",
         "order": 15
      },
      {
         "adult": false,
         "gender": 1,
         "id": 933716,
         "known_for_department": "Acting",
         "name": "Morgana King",
         "original_name": "Morgana King",
         "popularity": 2.881,
         "profile_path": "/1zzGZpZqedECtHMwfFIqd51nncM.jpg",
         "cast_id": 162,
         "character": "Mama Corleone",
         "credit_id": "6489ac82e272600107248470",
         "order": 16
      },
      {
         "adult": false,
         "gender": 2,
         "id": 106811,
         "known_for_department": "Acting",
         "name": "Lenny Montana",
         "original_name": "Lenny Montana",
         "popularity": 4.751,
         "profile_path": "/3R52Zh3MBCaSPqmcyWcD1Y0N4wo.jpg",
         "cast_id": 163,
         "character": "Luca Brasi",
         "credit_id": "6489ac90d2b20900ca220c08",
         "order": 17
      },
      {
         "adult": false,
         "gender": 2,
         "id": 99724,
         "known_for_department": "Acting",
         "name": "John Martino",
         "original_name": "John Martino",
         "popularity": 3.841,
         "profile_path": "/3c8BOgJ8UdHi5x5BS3lYnFngxB5.jpg",
         "cast_id": 164,
         "character": "Paulie Gatto",
         "credit_id": "6489ac9dd2b20900ca220c0f",
         "order": 18
      },
      {
         "adult": false,
         "gender": 2,
         "id": 1195877,
         "known_for_department": "Acting",
         "name": "Salvatore Corsitto",
         "original_name": "Salvatore Corsitto",
         "popularity": 2.123,
         "profile_path": "/79OfgwtdP5qsR1UX6ERkrdmRT8c.jpg",
         "cast_id": 165,
         "character": "Bonasera",
         "credit_id": "6489acaae375c000acc79705",
         "order": 19
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3174,
         "known_for_department": "Acting",
         "name": "Richard Bright",
         "original_name": "Richard Bright",
         "popularity": 9.814,
         "profile_path": "/potMaJ2u5PRjXZb7qF9lSW1ldNZ.jpg",
         "cast_id": 166,
         "character": "Neri",
         "credit_id": "6489acc2bf31f25054b828e4",
         "order": 20
      },
      {
         "adult": false,
         "gender": 2,
         "id": 20752,
         "known_for_department": "Acting",
         "name": "Alex Rocco",
         "original_name": "Alex Rocco",
         "popularity": 17.241,
         "profile_path": "/uAG4qvYhYHuCyyXGm3lqC4o6ujc.jpg",
         "cast_id": 167,
         "character": "Moe Greene",
         "credit_id": "6489acd1d2b20900ad3ec8cf",
         "order": 21
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3414,
         "known_for_department": "Acting",
         "name": "Tony Giorgio",
         "original_name": "Tony Giorgio",
         "popularity": 8.878,
         "profile_path": "/1uhgwgjoX7WaakEOBmtBRJKtgEB.jpg",
         "cast_id": 168,
         "character": "Bruno Tattaglia",
         "credit_id": "6489ad08bf31f25055a33b08",
         "order": 22
      },
      {
         "adult": false,
         "gender": 2,
         "id": 82779,
         "known_for_department": "Acting",
         "name": "Vito Scotti",
         "original_name": "Vito Scotti",
         "popularity": 12.225,
         "profile_path": "/vZJVyk2k8yCqLbpG4b9R22IYjSO.jpg",
         "cast_id": 169,
         "character": "Nazorine",
         "credit_id": "6489ad166f8d9501023e6cb2",
         "order": 23
      },
      {
         "adult": false,
         "gender": 1,
         "id": 982089,
         "known_for_department": "Acting",
         "name": "Tere Livrano",
         "original_name": "Tere Livrano",
         "popularity": 2.689,
         "profile_path": "/mSBI5B8t5WdA1vY82YlcySTopam.jpg",
         "cast_id": 170,
         "character": "Theresa Hagen",
         "credit_id": "6489ad23d2b20900ad3ec8f9",
         "order": 24
      },
      {
         "adult": false,
         "gender": 2,
         "id": 3413,
         "known_for_department": "Acting",
         "name": "Victor Rendina",
         "original_name": "Victor Rendina",
         "popularity": 5.081,
         "profile_path": "/vuNdsjDpgom80WBdB2WBTWuEIuM.jpg",
         "cast_id": 171,
         "character": "Philip Tattaglia",
         "credit_id": "6489ad306f8d9500c88beb2c",
         "order": 25
      },
      {
         "adult": false,
         "gender": 1,
         "id": 167363,
         "known_for_department": "Acting",
         "name": "Jeannie Linero",
         "original_name": "Jeannie Linero",
         "popularity": 2.191,
         "profile_path": null,
         "cast_id": 172,
         "character": "Lucy Mancini",
         "credit_id": "6489ad4f6f8d95011f2439db",
         "order": 26
      },
      {
         "adult": false,
         "gender": 1,
         "id": 160728,
         "known_for_department": "Acting",
         "name": "Julie Gregg",
         "original_name": "Julie Gregg",
         "popularity": 11.596,
         "profile_path": "/8Kx71BnZNtpzb86jH7fcArWhJBh.jpg",
         "cast_id": 173,
         "character": "Sandra Corleone",
         "credit_id": "6489ad696f8d9500c88beb4e",
         "order": 27
      },
      {
         "adult": false,
         "gender": 1,
         "id": 4111331,
         "known_for_department": "Acting",
         "name": "Ardell Sheridan",
         "original_name": "Ardell Sheridan",
         "popularity": 1.14,
         "profile_path": null,
         "cast_id": 174,
         "character": "Mrs. Clemenza",
         "credit_id": "6489adb8bf31f25054b8295f",
         "order": 28
      },
      {
         "adult": false,
         "gender": 1,
         "id": 3145,
         "known_for_department": "Acting",
         "name": "Simonetta Stefanelli",
         "original_name": "Simonetta Stefanelli",
         "popularity": 16.995,
         "profile_path": "/sVDrhgxuE6SHnj7q07OG6ywPUYR.jpg",
         "cast_id": 175,
         "character": "Apollonia - Sicilian Sequence",
         "credit_id": "6489ae04bf31f25055a33b87",
         "order": 29
      },
      {
         "adult": false,
         "gender": 2,
         "id": 27647,
         "known_for_department": "Acting",
         "name": "Angelo Infanti",
         "original_name": "Angelo Infanti",
         "popularity": 5.653,
         "profile_path": "/dkRVpiDj9YyiuM15XZKT11zZBIR.jpg",
         "cast_id": 176,
         "character": "Fabrizio - Sicilian Sequence",
         "credit_id": "6489ae14d2b20900ca220cca",
         "order": 30
      },
      {
         "adult": false,
         "gender": 2,
         "id": 24604,
         "known_for_department": "Acting",
         "name": "Corrado Gaipa",
         "original_name": "Corrado Gaipa",
         "popularity": 2.081,
         "profile_path": "/7vR2BOdVw9FwJKjgpcisjKEytnL.jpg",
         "cast_id": 177,
         "character": "Don Tommasino - Sicilian Sequence",
         "credit_id": "6489ae21d2b20900ca220cd4",
         "order": 31
      },
      {
         "adult": false,
         "gender": 2,
         "id": 44860,
         "known_for_department": "Acting",
         "name": "Franco Citti",
         "original_name": "Franco Citti",
         "popularity": 6.43,
         "profile_path": "/mttQPjOHaql4RKsfYriUA7HuROE.jpg",
         "cast_id": 178,
         "character": "Calo - Sicilian Sequence",
         "credit_id": "6489ae2e6f8d9500c88bebcf",
         "order": 32
      },
      {
         "adult": false,
         "gender": 2,
         "id": 119431,
         "known_for_department": "Acting",
         "name": "Saro Urz\u00ec",
         "original_name": "Saro Urz\u00ec",
         "popularity": 2.938,
         "profile_path": "/wp88yz8T1TJcw5egiDu1m5a302D.jpg",
         "cast_id": 179,
         "character": "Vitelli - Sicilian Sequence",
         "credit_id": "6489ae3ce2726000afc4c253",
         "order": 33
      },
      {
         "adult": false,
         "gender": 2,
         "id": 38803,
         "known_for_department": "Writing",
         "name": "Roman Coppola",
         "original_name": "Roman Coppola",
         "popularity": 7.801,
         "profile_path": "/dq454EhrDVKBsiYzuLr0IkKa18v.jpg",
         "cast_id": 182,
         "character": "Boy on Street Who Attended Funeral (uncredited)",
         "credit_id": "6489af3ce2726001287c0ab0",
         "order": 34
      },
      {
         "adult": false,
         "gender": 1,
         "id": 1769,
         "known_for_department": "Directing",
         "name": "Sofia Coppola",
         "original_name": "Sofia Coppola",
         "popularity": 13.517,
         "profile_path": "/dzHC2LxmarkBxWLhjp2DRa5oCev.jpg",
         "cast_id": 181,
         "character": "Michael Francis Rizzi (uncredited)",
         "credit_id": "6489af2de375c000acc797fe",
         "order": 35
      },
      {
         "adult": false,
         "gender": 0,
         "id": 1209294,
         "known_for_department": "Acting",
         "name": "Don Costello",
         "original_name": "Don Costello",
         "popularity": 1.228,
         "profile_path": null,
         "cast_id": 183,
         "character": "Don Victor Stracci (uncredited)",
         "credit_id": "6489af7abf31f2505883d309",
         "order": 36
      },
      {
         "adult": false,
         "gender": 1,
         "id": 126072,
         "known_for_department": "Acting",
         "name": "Italia Coppola",
         "original_name": "Italia Coppola",
         "popularity": 1.316,
         "profile_path": null,
         "cast_id": 184,
         "character": "Extra in Wedding Scene (uncredited)",
         "credit_id": "6489afb46f8d95011f243b21",
         "order": 37
      },
      {
         "adult": false,
         "gender": 2,
         "id": 2870,
         "known_for_department": "Production",
         "name": "Gray Frederickson",
         "original_name": "Gray Frederickson",
         "popularity": 2.649,
         "profile_path": null,
         "cast_id": 195,
         "character": "Cowboy on the Set at Woltz's Studio (uncredited)",
         "credit_id": "6489b195e375c00139c270d3",
         "order": 38
      },
      {
         "adult": false,
         "gender": 2,
         "id": 160621,
         "known_for_department": "Acting",
         "name": "Ron Gilbert",
         "original_name": "Ron Gilbert",
         "popularity": 4.051,
         "profile_path": "/qrY6w2k0YpuMB2yTCOv6cxeQtmw.jpg",
         "cast_id": 185,
         "character": "Usher in Bridal Party (uncredited)",
         "credit_id": "6489afe46f8d95013c752d10",
         "order": 39
      },
      {
         "adult": false,
         "gender": 2,
         "id": 1233541,
         "known_for_department": "Acting",
         "name": "Sonny Grosso",
         "original_name": "Sonny Grosso",
         "popularity": 2.437,
         "profile_path": null,
         "cast_id": 202,
         "character": "Cop Outside Hospital (uncredited)",
         "credit_id": "6489b33fe272600107248730",
         "order": 40
      },
      {
         "adult": false,
         "gender": 2,
         "id": 20973,
         "known_for_department": "Acting",
         "name": "Louis Guss",
         "original_name": "Louis Guss",
         "popularity": 5.198,
         "profile_path": "/hz5Akuh4QcqitlifYwDiZ9ut6Tr.jpg",
         "cast_id": 180,
         "character": "Don Zaluchi (uncredited)",
         "credit_id": "6489af11e375c000ff4ab5f2",
         "order": 41
      },
      {
         "adult": false,
         "gender": 2,
         "id": 1068099,
         "known_for_department": "Acting",
         "name": "Randy Jurgensen",
         "original_name": "Randy Jurgensen",
         "popularity": 2.201,
         "profile_path": "/xRoN79wRLndTMCJoaBSsdjQVIzI.jpg",
         "cast_id": 186,
         "character": "Sonny's Killer #1 (uncredited)",
         "credit_id": "6489affed2b209014e0b8fdb",
         "order": 42
      },
      {
         "adult": false,
         "gender": 2,
         "id": 55672,
         "known_for_department": "Acting",
         "name": "Tony King",
         "original_name": "Tony King",
         "popularity": 2.356,
         "profile_path": "/hOVVHEyc6euuuRhCLo6Q5YE4lLz.jpg",
         "cast_id": 196,
         "character": "Tony - Stablehand (uncredited)",
         "credit_id": "6489b214e375c000ff4ab714",
         "order": 43
      },
      {
         "adult": false,
         "gender": 2,
         "id": 61241,
         "known_for_department": "Acting",
         "name": "Tony Lip",
         "original_name": "Tony Lip",
         "popularity": 5.276,
         "profile_path": "/6xz6XmjgiCCOm067OzWYziD4Mxa.jpg",
         "cast_id": 206,
         "character": "Wedding Guest (uncredited)",
         "credit_id": "6489b6276f8d9500e5015933",
         "order": 44
      },
      {
         "adult": false,
         "gender": 2,
         "id": 1503036,
         "known_for_department": "Acting",
         "name": "Joe Lo Grippo",
         "original_name": "Joe Lo Grippo",
         "popularity": 1.268,
         "profile_path": null,
         "cast_id": 188,
         "character": "Sonny's Bodyguard (uncredited)",
         "credit_id": "6489b0736f8d9500afdf2448",
         "order": 45
      },
      {
         "adult": false,
         "gender": 2,

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

<a id="section24"></a>
### 2.4 People Data

A pre-built MongoDB collection `dbmovies.people` holds profile information for the most important people across the credits — name, birthdate, short biography. The collection is served via an HTTP endpoint backed by MongoDB Atlas Data API.

The request payload accepts a `projection` dict (fields to return) and a `filter` dict (selection criteria), plus an API key for authentication.

<div class="alert alert-block alert-info">
<i class="fa fa-info-circle" aria-hidden="true"></i>
**Note:** TMDb also exposes per-person metadata via `GET /person/{person_id}`, using the TMDb-native ID.
</div>

Fetch the `name`, `biography`, and `profile_path` for the person with `id == 3084`. Store the returned `document` in `mb_data`.

In [7]:
url = "https://eu-west-2.aws.data.mongodb-api.com/app/data-lioff/endpoint/data/v1/action/findOne"

payload = json.dumps({
    "collection": "people",
    "database": "cidaendb",
    "dataSource": "Cluster0",
    "projection": {
        "name": 1,
        "biography:":1,
        "profile_path":1
    },
    "filter": {
        "id": 3084
    }    
})
headers = {
  'Content-Type': 'application/json',
  'Access-Control-Request-Headers': '*',
  'api-key':'21fgdRPu3acdhNED6zfRgHsI5KCcF3OaNZgVWVs6Ayt8UyqIXh3NcLxzcgmDhOK7',
}

response = requests.request("POST", url, headers=headers, data=payload)

mb_data = response.json()['document']
mb_data

{'_id': '673b67a01520298180dd968a',
 'name': 'Marlon Brando',
 'profile_path': '/fuTEPMsBtV1zE98ujPONbKiYDc2.jpg'}

`profile_path` is a relative URL for the person's profile photo, e.g. `http://image.tmdb.org/t/p/w185/<profile_path>`.

In [10]:
Image = ('http://image.tmdb.org/t/p/w185/'+mb_data['profile_path'])
Image

'http://image.tmdb.org/t/p/w185//fuTEPMsBtV1zE98ujPONbKiYDc2.jpg'

The same endpoint supports a `find()` call that returns every matching document. With no filter or projection it returns the full collection. We set `limit: 10000` to override the default pagination cap.

Download all people records and store them under the `documents` key as `people_data`.

In [10]:
import json
import requests
url = "https://eu-west-2.aws.data.mongodb-api.com/app/data-lioff/endpoint/data/v1/action/find"

payload = json.dumps({
    "collection": "people",
    "database": "cidaendb",
    "dataSource": "Cluster0",
    "limit" :10000,
})

headers = {
  'Content-Type': 'application/json',
  'Access-Control-Request-Headers': '*',
  'api-key':'21fgdRPu3acdhNED6zfRgHsI5KCcF3OaNZgVWVs6Ayt8UyqIXh3NcLxzcgmDhOK7',
}

response = requests.request("POST", url, headers=headers, data=payload)
people_data = response.json()['documents']
len(people_data)

6406

Store `people_data` in the `dbmovies.people` collection. Since the collection is small, a pre-insert `.drop()` keeps the load idempotent.

In [50]:
collection = dbmovies["people"]
collection.insert_many(people_data)

KeyboardInterrupt:

In [12]:
collection_people = dbmovies["people"]
collection_credits = dbmovies['credits']

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

---

<a id="section3"></a>
## 3. Building a Structured Dataset

At this point we have:

* `df_movies` — basic movie metadata from IMDb plus ratings
* `dbmovies.movies` — TMDb enrichment (budget, revenue, etc.)
* `dbmovies.credits` — raw credits JSON per movie
* `dbmovies.people` — profile information for people in the credits

The next step is to reshape this into a form suitable for analysis — either as tidy DataFrames, as a relational database, or both. We produce both.

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

<a id="section31"></a>
### 3.1 DataFrame Construction

First, we augment `df_movies` with a few fields from `dbmovies.movies`. We rename the DataFrame's index to `imdb_id` to make the join mechanics explicit.

In [21]:
df_movies.index.rename('imdb_id', inplace=True)
df_movies

,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
imdb_id,,,,,,,,,,
tt0000417,short,A Trip to the Moon,Le voyage dans la lune,0,1902,<NA>,13,"Action,Adventure,Comedy",8.1,57200
tt0010323,movie,The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,0,1920,<NA>,67,"Horror,Mystery,Thriller",8.0,71863
tt0012349,movie,The Kid,The Kid,0,1921,<NA>,68,"Comedy,Drama,Family",8.2,137619
tt0013442,movie,Nosferatu: A Symphony of Horror,"Nosferatu, eine Symphonie des Grauens",0,1922,<NA>,94,"Fantasy,Horror",7.8,108889
tt0015324,movie,Sherlock Jr.,Sherlock Jr.,0,1924,<NA>,45,"Action,Comedy,Romance",8.2,58967
...,...,...,...,...,...,...,...,...,...,...
tt9844522,movie,Escape Room: Tournament of Champions,Escape Room: Tournament of Champions,0,2021,<NA>,88,"Action,Adventure,Horror",5.7,62208
tt9866072,movie,Holidate,Holidate,0,2020,<NA>,104,"Comedy,Romance",6.1,80693
tt9893250,movie,I Care a Lot,I Care a Lot,0,2020,<NA>,118,"Comedy,Crime,Drama",6.4,150028
tt9898836,tvEpisode,Perfect Game,Perfect Game,0,2019,<NA>,24,"Action,Adventure,Animation",9.8,85407
tt9906260,tvEpisode,Hero,Hero,0,2019,<NA>,24,"Action,Adventure,Animation",9.7,138355

For simplicity, we pull just `budget` and `revenue` from the TMDb staging collection. We then drop the columns `titleType`, `originalTitle`, and `endYear`, which either carry a single constant value after filtering or aren't relevant to the downstream model.

In [22]:
movies_collection = dbmovies["movies"]
movies_data = movies_collection.find({},{"imdb_id":1, "budget":1,"revenue":1,"_id":0})
movies_data = pd.DataFrame(list(movies_data))
movies_data.set_index("imdb_id",inplace=True)
movies_data.head()

df_movies = df_movies.merge (movies_data, on = "imdb_id",how = "inner") #hago un inner merge para mantener solo los casos en los que existen datos en movies_data
df_movies.head()

,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,budget,revenue
imdb_id,,,,,,,,,,,,
tt0000417,short,A Trip to the Moon,Le voyage dans la lune,0,1902,<NA>,13,"Action,Adventure,Comedy",8.1,57200,5985,0
tt0010323,movie,The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,0,1920,<NA>,67,"Horror,Mystery,Thriller",8.0,71863,18000,8811
tt0012349,movie,The Kid,The Kid,0,1921,<NA>,68,"Comedy,Drama,Family",8.2,137619,250000,2500000
tt0013442,movie,Nosferatu: A Symphony of Horror,"Nosferatu, eine Symphonie des Grauens",0,1922,<NA>,94,"Fantasy,Horror",7.8,108889,0,19054
tt0015324,movie,Sherlock Jr.,Sherlock Jr.,0,1924,<NA>,45,"Action,Comedy,Romance",8.2,58967,0,0

In [26]:
df_movies = df_movies[df_movies["titleType"] == "movie"]
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4265 entries, tt0010323 to tt9893250
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   titleType       4265 non-null   string
 1   primaryTitle    4265 non-null   object
 2   originalTitle   4265 non-null   string
 3   isAdult         4265 non-null   Int32
 4   startYear       4265 non-null   Int32
 5   endYear         0 non-null      Int32
 6   runtimeMinutes  4265 non-null   Int32
 7   genres          4265 non-null   string
 8   averageRating   4265 non-null   float64
 9   numVotes        4265 non-null   int64
 10  budget          4265 non-null   int64
 11  revenue         4265 non-null   int64
dtypes: Int32(4), float64(1), int64(3), object(1), string(3)
memory usage: 383.2+ KB

In [27]:
df_movies = df_movies.drop(columns=['titleType', 'originalTitle', 'endYear'])

Pull `id`, `name`, `gender`, `popularity`, and `place_of_birth` from `dbmovies.people`, suppressing `_id` explicitly for hygiene. Store the cursor in `people_data`.

In [28]:
collection_people = dbmovies["people"]
projection = {"id":1,"name":1,"gender":1,"populariy":1,"place_of_birth":1,"_id":0}
people_data = list(collection_people.find({},projection))
people_data[0:5]

[{'gender': 2,
  'id': 13848,
  'name': 'Charlie Chaplin',
  'place_of_birth': 'Walworth, London, England, UK'},
 {'gender': 2,
  'id': 9076,
  'name': 'F. W. Murnau',
  'place_of_birth': 'Bielefeld, North-Rhine-Westphalia, Germany'},
 {'gender': 2,
  'id': 8635,
  'name': 'Buster Keaton',
  'place_of_birth': 'Piqua, Kansas, USA'},
 {'gender': 2,
  'id': 11572,
  'name': 'Carl Theodor Dreyer',
  'place_of_birth': 'Copenhagen, Denmark'},
 {'gender': 2,
  'id': 30008,
  'name': 'Leo McCarey',
  'place_of_birth': 'Los Angeles, California, USA'}]

For clarity, we rename the incoming `id` field to `people_id` before building the DataFrame.

In [29]:
for person_data in people_data:
    person_data['people_id'] = person_data.pop('id')

Build `df_people` from `people_data`, using `people_id` as the index.

In [30]:
df_people = pd.DataFrame(people_data).set_index("people_id")
df_people

,gender,name,place_of_birth
people_id,,,
13848,2,Charlie Chaplin,"Walworth, London, England, UK"
9076,2,F. W. Murnau,"Bielefeld, North-Rhine-Westphalia, Germany"
8635,2,Buster Keaton,"Piqua, Kansas, USA"
11572,2,Carl Theodor Dreyer,"Copenhagen, Denmark"
30008,2,Leo McCarey,"Los Angeles, California, USA"
...,...,...,...
35027,3,Ryan Simpkins,"New York City, New York, USA"
1377686,1,Sarah Goldberg,"Vancouver, British Columbia, Canada"
6198,2,Vondie Curtis-Hall,"Detroit, Michigan, USA"
2241214,1,Linda May,None
59017,1,Jurnee Smollett,"New York City, New York, USA"

Finally, `dbmovies.credits` holds the full credits payloads — roughly 150 MB total. Most of that is irrelevant for our schema, so we pull down only:

* `imdb_id`
* director (the `crew` entries with `job == 'Director'`)
* the top 3 billed cast members (`cast` entries with `order` in {0, 1, 2})

Download the trimmed payload and store it in a list `credits_data`.

In [31]:
collection_credits= dbmovies["credits"]

In [32]:
pipeline = [
    {
        '$project': {
            '_id': 0,
            'imdb_id': 1,
            'cast': {
                '$filter': {
                    'input': '$cast',
                    'as': 'cast_member',
                    'cond': {'$lte': ['$$cast_member.order', 2]}
                }
            },
            'crew': {
                '$filter': {
                    'input': '$crew',
                    'as': 'crew_member',
                    'cond': {'$eq': ['$$crew_member.job', 'Director']}
                }
            }
        }
    },
    {
        '$project': {
            'imdb_id': 1,
            'cast': {
                '$map': {
                    'input': '$cast',
                    'as': 'cast_member',
                    'in': {
                        'id': '$$cast_member.id',
                        'name': '$$cast_member.name'
                    }
                }
            },
            'crew': {
                '$map': {
                    'input': '$crew',
                    'as': 'crew_member',
                    'in': {
                        'id': '$$crew_member.id',
                        'name': '$$crew_member.name'
                    }
                }
            }
        }
    }
]

credits_data = list(dbmovies.credits.aggregate(pipeline))

In [33]:
pd.DataFrame(credits_data).head().set_index('imdb_id')

,cast,crew
imdb_id,,
tt0000417,"[{'id': 11523, 'name': 'Georges Méliès'}, {'id...","[{'id': 11523, 'name': 'Georges Méliès'}]"
tt0010323,"[{'id': 3000, 'name': 'Werner Krauss'}, {'id':...","[{'id': 2991, 'name': 'Robert Wiene'}]"
tt0012349,"[{'id': 13848, 'name': 'Charlie Chaplin'}, {'i...","[{'id': 13848, 'name': 'Charlie Chaplin'}]"
tt0013442,"[{'id': 9839, 'name': 'Max Schreck'}, {'id': 9...","[{'id': 9076, 'name': 'F. W. Murnau'}]"
tt0015324,"[{'id': 8635, 'name': 'Buster Keaton'}, {'id':...","[{'id': 8635, 'name': 'Buster Keaton'}]"

Now we build `df_credits` — one row per (movie, person, role) triple — with three columns:

* `imdb_id` — IMDb movie identifier
* `people_id` — TMDb person identifier
* `rol` — `cast` or `director`

We assemble it from two intermediate frames (`df_cast` and `df_crew`), then concatenate.

In [34]:
aux_cast = [(credit_mov['imdb_id'], [cast_mem['id'] for cast_mem in credit_mov['cast']]) for credit_mov in credits_data]
aux_crew = [(credit_mov['imdb_id'], [crew_mem['id'] for crew_mem in credit_mov['crew']]) for credit_mov in credits_data]

aux_cast[:3]

#[('tt0010323', [3000, 3001, 590591]),
# ('tt0012349', [13848, 19426, 21301]),
# ('tt0013442', [9839, 9840, 9841])]

[('tt0000417', [11523, 11645, 1271225]),
 ('tt0010323', [3000, 3001, 590591]),
 ('tt0012349', [13848, 19426, 63378])]

Build `df_cast` from the cast side of `credits_data` by exploding the list of three IDs into three rows per movie.

In [35]:
df_cast = pd.DataFrame(aux_cast,columns=['imdb_id','cast']).set_index('imdb_id')
df_cast

                                 cast
imdb_id
tt0000417     [11523, 11645, 1271225]
tt0010323        [3000, 3001, 590591]
tt0012349       [13848, 19426, 63378]
tt0013442          [9839, 9840, 9841]
tt0015324        [8635, 14920, 10530]
...                               ...
tt9783600      [74568, 996701, 59017]
tt9784798    [206919, 1200864, 88124]
tt9844522  [1353827, 116088, 1789788]
tt9866072      [34847, 972356, 52775]
tt9893250     [10882, 22970, 1222992]

[4295 rows x 1 columns]

Build `df_crew` from `aux_crew` the same way.

In [36]:
df_crew = pd.DataFrame(aux_crew,columns=['imdb_id','crew']).set_index('imdb_id')
df_crew

                crew
imdb_id
tt0000417    [11523]
tt0010323     [2991]
tt0012349    [13848]
tt0013442     [9076]
tt0015324     [8635]
...              ...
tt9783600    [86270]
tt9784798  [1140231]
tt9844522  [1306608]
tt9866072    [61175]
tt9893250   [111588]

[4295 rows x 1 columns]

Concatenate `df_cast` and `df_crew` into `df_credits`, adding a `rol` column that records the source (`cast` or `director`).

In [37]:
# 1. Concatenate DataFrames with source keys
df_credits = pd.concat([df_cast, df_crew], 
                      keys=['cast', 'director'],
                      names=['rol', 'imdb_id'])

# 2. Reset the index to surface 'rol' as a column
df_credits = df_credits.reset_index().set_index('imdb_id')

df_credits

                rol                     cast       crew
imdb_id
tt0000417      cast  [11523, 11645, 1271225]        NaN
tt0010323      cast     [3000, 3001, 590591]        NaN
tt0012349      cast    [13848, 19426, 63378]        NaN
tt0013442      cast       [9839, 9840, 9841]        NaN
tt0015324      cast     [8635, 14920, 10530]        NaN
...             ...                      ...        ...
tt9783600  director                      NaN    [86270]
tt9784798  director                      NaN  [1140231]
tt9844522  director                      NaN  [1306608]
tt9866072  director                      NaN    [61175]
tt9893250  director                      NaN   [111588]

[8590 rows x 3 columns]

In [38]:
df_people.head()

,gender,name,place_of_birth
people_id,,,
13848,2,Charlie Chaplin,"Walworth, London, England, UK"
9076,2,F. W. Murnau,"Bielefeld, North-Rhine-Westphalia, Germany"
8635,2,Buster Keaton,"Piqua, Kansas, USA"
11572,2,Carl Theodor Dreyer,"Copenhagen, Denmark"
30008,2,Leo McCarey,"Los Angeles, California, USA"

In [45]:
df_people_data = pd.DataFrame(people_data)
df_people_data.set_index('people_id',inplace=True)
df_people_data.head()

,gender,name,place_of_birth
people_id,,,
13848,2,Charlie Chaplin,"Walworth, London, England, UK"
9076,2,F. W. Murnau,"Bielefeld, North-Rhine-Westphalia, Germany"
8635,2,Buster Keaton,"Piqua, Kansas, USA"
11572,2,Carl Theodor Dreyer,"Copenhagen, Denmark"
30008,2,Leo McCarey,"Los Angeles, California, USA"

Some credits reference people whose profile data we weren't able to fetch. We drop those rows to maintain referential integrity with the `PEOPLE` table we're about to create.

In [110]:
valid_people_ids = set(df_people['people_id'])  
df_credits = df_credits[df_credits['people_id'].isin(valid_people_ids)]

In [111]:
df_credits.head()

     imdb_id   rol people_id
0  tt0010323  cast      3000
1  tt0010323  cast      3001
2  tt0010323  cast    590591
3  tt0012349  cast     13848
4  tt0012349  cast     19426

In [ ]:
df_people.head()

,gender,name,place_of_birth
people_id,,,
13848,2,Charlie Chaplin,"Walworth, London, England, UK"
9076,2,F. W. Murnau,"Bielefeld, North-Rhine-Westphalia, Germany"
8635,2,Buster Keaton,"Piqua, Kansas, USA"
11572,2,Carl Theodor Dreyer,"Copenhagen, Denmark"
30008,2,Leo McCarey,"Los Angeles, California, USA"

In [56]:
df_credits.head()

            rol                   cast crew
imdb_id
tt0000417  cast                     []  NaN
tt0010323  cast   [3000, 3001, 590591]  NaN
tt0012349  cast  [13848, 19426, 63378]  NaN
tt0013442  cast     [9839, 9840, 9841]  NaN
tt0015324  cast   [8635, 14920, 10530]  NaN

In [57]:
df_credits = df_credits.explode('cast')
df_credits = df_credits.explode('crew')

df_credits['people_id'] = df_credits['cast'].combine_first(df_credits['crew'])

df_credits = df_credits.drop(columns=['cast', 'crew']).dropna().reset_index()

In [112]:
df_credits.set_index('imdb_id',inplace=True)

In [113]:
df_credits.head()

            rol people_id
imdb_id
tt0010323  cast      3000
tt0010323  cast      3001
tt0010323  cast    590591
tt0012349  cast     13848
tt0012349  cast     19426

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

<a id="section32"></a>
### 3.2 Relational Database Schema and Load

With `df_movies`, `df_credits`, and `df_people` in hand, we load the data into a SQLite relational database. The schema has three tables and enforces referential integrity via foreign keys.

* **`MOVIES`** — `imdb_id` (PK), `primaryTitle`, `isAdult`, `startYear`, `runtimeMinutes`, `genres`, `averageRating`, `numVotes`, `budget`, `revenue`
* **`PEOPLE`** — `people_id` (PK), `gender`, `name`, `place_of_birth`, `popularity`
* **`CREDITS`** — `imdb_id`, `people_id`, `rol` (many-to-many link; FKs to `MOVIES.imdb_id` and `PEOPLE.people_id`)

<div class="alert alert-block alert-danger">
<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
pandas' `to_sql()` can't declare primary keys or foreign keys, and SQLite doesn't support `ALTER TABLE ADD CONSTRAINT`. Workaround: define the schema up front with raw SQL `CREATE TABLE` statements, then bulk-load the DataFrames with `to_sql(..., if_exists='append')`.
</div>

In [62]:
from sqlalchemy import create_engine, text
import os

# Start fresh each run — a conditional drop could also work here
# to make the load idempotent.
try:
    os.remove('./data/movies.db')
except:
    pass

# Open a SQLite database connection
engine = create_engine('sqlite:///data/movies.db')

In [71]:
with engine.connect() as connection:
    connection.execute(text("PRAGMA foreign_keys = ON"))

In [69]:
with engine.connect() as connection:
    connection.execute(text("PRAGMA foreign_keys = ON"))
    

    query = text(""" CREATE TABLE IF NOT EXISTS MOVIES(
                        imdb_id TEXT PRIMARY KEY, 
                        primaryTitle TEXT, 
                        isAdult INTEGER, 
                        startYear INTEGER, 
                        runtimeMinutes INTEGER, 
                        genres TEXT, 
                        averageRating FLOAT, 
                        numVotes BIGINT, 
                        budget BIGINT, 
                        revenue BIGINT) 
                        """ )
    

    connection.execute(query)
    
    
    query = text(""" CREATE TABLE IF NOT EXISTS PEOPLE (
                        people_id BIGINT PRIMARY KEY, 
                        gender BIGINT, 
                        name TEXT, 
                        place_of_birth TEXT, 
                        popularity FLOAT) 
                """ )
    
    connection.execute(query)   
    
    
        
    query = text(""" CREATE TABLE IF NOT EXISTS CREDITS (
                        rol TEXT NOT NULL,
                        imdb_id TEXT NOT NULL,
                        people_id BIGINT NOT NULL,
                        FOREIGN KEY (imdb_id) REFERENCES MOVIES(imdb_id),
                        FOREIGN KEY (people_id) REFERENCES PEOPLE(people_id)
                        )
                 """)
    
    connection.execute(query)

In [78]:
df_movies.head()

,primaryTitle,isAdult,startYear,runtimeMinutes,genres,averageRating,numVotes,budget,revenue
imdb_id,,,,,,,,,
tt0010323,The Cabinet of Dr. Caligari,0,1920,67,"Horror,Mystery,Thriller",8.0,71863,18000,8811
tt0012349,The Kid,0,1921,68,"Comedy,Drama,Family",8.2,137619,250000,2500000
tt0013442,Nosferatu: A Symphony of Horror,0,1922,94,"Fantasy,Horror",7.8,108889,0,19054
tt0015324,Sherlock Jr.,0,1924,45,"Action,Comedy,Romance",8.2,58967,0,0
tt0015648,Battleship Potemkin,0,1925,66,"Drama,History,Thriller",7.9,62361,0,45100

Load `df_movies`, `df_people`, and `df_credits` into the pre-created tables using `if_exists='append'` so the schema stays untouched.

In [73]:
df_movies.to_sql('MOVIES',engine,if_exists='append')

4265

In [74]:
df_people.to_sql('PEOPLE',engine,if_exists='append')

6406

In [ ]:
df_credits_filtered.to_sql('CREDITS',engine,if_exists='append')

IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: INSERT INTO "CREDITS" (imdb_id, rol, people_id) VALUES (?, ?, ?)]
[parameters: [('tt0010323', 'cast', 3000), ('tt0010323', 'cast', 3001), ('tt0010323', 'cast', 590591), ('tt0012349', 'cast', 13848), ('tt0012349', 'cast', 19426), ('tt0012349', 'cast', 63378), ('tt0013442', 'cast', 9839), ('tt0013442', 'cast', 9840)  ... displaying 10 of 17414 total bound parameter sets ...  ('tt9866072', 'director', 61175), ('tt9893250', 'director', 111588)]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [ ]:
credit_ids = set(df_credits_filtered["people_id"].unique())
people_ids = set(df_people["people_id"].unique())

missing_in_people = credit_ids - people_ids 
missing_in_credits = people_ids - credit_ids  

print("IDs in df_credits but missing in df_people:", missing_in_people)
print("IDs in df_people but missing in df_credits:", missing_in_credits)

IDs in df_credits but missing in df_people: set()
IDs in df_people but missing in df_credits: {1365769, 1375501, 25872, 58001, 12178, 1652371, 6295, 86424, 537, 2221, 79405, 1515055, 1442866, 1846, 38582, 585655, 1487546, 187, 9661, 21693, 136127, 1901375, 110916, 54470, 92614, 3664, 11478, 31581, 1898, 84076, 9070, 6385, 63992, 21629}

In [121]:
# Get unique people_id values from df_people
valid_people_ids = set(df_people["people_id"].unique())

# Filter df_credits to remove rows where people_id is missing in df_people
df_credits_filtered = df_credits[df_credits["people_id"].isin(valid_people_ids)]

In [126]:
# Get unique IDs from both dataframes
people_ids = set(df_people["people_id"].unique())
credit_ids = set(df_credits["people_id"].unique())

# Find missing IDs
missing_ids = {'1898', '92614', '63992', '11478', '2221', '1652371', '6295', '3664', 
               '31581', '6385', '58001', '1442866', '12178', '9070', '585655', 
               '1365769', '1901375', '25872', '86424', '54470', '1375501', '136127', 
               '537', '1515055', '187', '1487546', '84076', '110916', '38582', 
               '79405', '1846', '21629', '21693', '9661'}

# Remove rows where people_id is in missing_ids
df_credits_cleaned = df_credits[~df_credits["people_id"].isin(missing_ids)].copy()

# Verify the removal
remaining_ids = set(df_credits_cleaned["people_id"].unique())
new_missing = remaining_ids - people_ids

print("Number of rows in original df_credits:", len(df_credits))
print("Number of rows in cleaned df_credits:", len(df_credits_cleaned))
print("Number of IDs removed:", len(missing_ids))
print("Any remaining missing IDs:", new_missing)

Number of rows in original df_credits: 17414
Number of rows in cleaned df_credits: 17414
Number of IDs removed: 34
Any remaining missing IDs: set()

In [128]:
df_credits_cleaned.to_sql('CREDITS',engine,if_exists='append')

IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: INSERT INTO "CREDITS" (imdb_id, rol, people_id) VALUES (?, ?, ?)]
[parameters: [('tt0010323', 'cast', '3000'), ('tt0010323', 'cast', '3001'), ('tt0010323', 'cast', '590591'), ('tt0012349', 'cast', '13848'), ('tt0012349', 'cast', '19426'), ('tt0012349', 'cast', '63378'), ('tt0013442', 'cast', '9839'), ('tt0013442', 'cast', '9840')  ... displaying 10 of 17414 total bound parameter sets ...  ('tt9866072', 'director', '61175'), ('tt9893250', 'director', '111588')]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [ ]:
engine.dispose()

We now have a small SQLite database with a clean normalized schema. It can be inspected programmatically (as we do below) or visually with [DB Browser for SQLite](https://sqlitebrowser.org/).

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

---

<a id="section4"></a>
## 4. Example Queries

A few analytical queries to validate the pipeline end-to-end.

From the DataFrames, find the ten cast members associated with the highest total box-office revenue.

In [ ]:
pd.options.display.max_rows = 10

# TODO: Build a DataFrame of the top 10 cast members by total movie revenue.
# Merge df_credits (rol == "cast") with df_movies on imdb_id, sum revenue per
# people_id, sort descending, take head(10), and merge with df_people for names.
pass

Using SQL against `data/movies.db`, list 2023 movies with average rating above 7.5.

In [ ]:
engine = create_engine('sqlite:///data/movies.db')  


# TODO: Query movies.db for 2023 releases with averageRating > 7.5
pd.read_sql(
    "SELECT primaryTitle, averageRating, numVotes FROM MOVIES WHERE startYear = 2023 AND averageRating > 7.5 ORDER BY averageRating DESC",
    engine,
)

Using SQL, list the ten highest-rated movies overall.

In [ ]:
# TODO: Query movies.db for the 10 highest-rated movies overall
pd.read_sql(
    "SELECT primaryTitle, startYear, averageRating, numVotes FROM MOVIES ORDER BY averageRating DESC LIMIT 10",
    engine,
)

Using SQL, list the director for each movie.

In [ ]:
# TODO: Join MOVIES -> CREDITS -> PEOPLE on director role
query = """
SELECT m.primaryTitle, p.name AS director
FROM MOVIES m
JOIN CREDITS c ON c.imdb_id = m.imdb_id AND c.rol = 'director'
JOIN PEOPLE p ON p.people_id = c.people_id
ORDER BY m.startYear DESC
LIMIT 20
"""

pd.read_sql(query, engine)

In [ ]:
engine.dispose()

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

---

<a id="section5"></a>
## 5. Conclusions

This project traced the full path from raw CSV/TSV exports through REST API enrichment, a NoSQL staging layer, pandas-based reshaping, and finally a clean relational schema suitable for analytical queries.

The workflow is a compact mirror of a real data engineering pipeline: heterogeneous sources → document lake → structured marts → analytics. Scaling up means orchestrating the extract-transform-load steps with purpose-built tools (Airflow, dbt, Spark) and swapping SQLite for a warehouse — but the shape of the problem stays the same.

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

---

<a id="sectionA"></a>
## A. Optional Extensions

Two natural follow-ons for extending this pipeline.

<a id="sectionA1"></a>
### A.1 Keywords

* `GET /movie/{imdb_id}/keywords` returns the keyword tags associated with each movie.
* Keywords for every movie in `df_movies` are also staged in the internal `cidaendb.keywords` collection (requires API key).

In [ ]:
api_key = '21fgdRPu3acdhNED6zfRgHsI5KCcF3OaNZgVWVs6Ayt8UyqIXh3NcLxzcgmDhOK7'

<a id="sectionA2"></a>
### A.2 TV Series and Episodes

* `data/imdb/title.episode.tsv.gz` contains episode metadata (series ID, season number, episode number) for each `tvEpisode` in `title.basics`.
* Enrichment via TMDb:
  * `GET /find/{imdb_id}?external_source=imdb_id` — resolve any IMDb ID to TMDb's native ID
  * `GET /tv/{series_id}` — series-level information
  * `GET /tv/{series_id}/season/{season}/episode/{episode}/external_ids` — per-episode information

In [ ]:
imdb_got = 'tt0944947'  # Game of Thrones
tmdb_got = 1399


imdb_bob = 'tt4283088'  # "Battle of the Bastards" episode
tmdb_bob = 1187404

<div align="right">
<a href="#indice">[back to contents]</a>
</div>

---